Validation login, finished
katalinapalma/Gallery pull request #45
Opened 2020-01-05 22:34 UTC by KarwanG94

fixed the last of it, gave it some styling aswell

2020-01-05 23:15 UTC, katalinapalma requested changes
Success och successful stavas med två s :) ändra det så det blir rätt annars ser det bra ut!

2020-01-06 20:18 UTC, katalinapalma approved these changes

2020-01-07 10:02 UTC, antman94 reviewed
om man skriver fel lösenord så står det user not found, borde stå incorrect password eller nåt istället?

2020-01-07 10:55 UTC, antman94 approved these changes
ok

2020-01-07 10:55 UTC, merged